services:
  university-bot:
    build: .
    container_name: university-chatbot
    ports:
      - "8001:8001"
    volumes:
      - ./data:/app/data
      - ./chroma_store:/app/chroma_store
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - CHROMA_PATH=/app/chroma_store
      - DATA_PATH=/app/data
